name: Delete All Except Workflows

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Delete everything except .github/workflows and .git
        run: |
          shopt -s extglob
          rm -rf !(.git|.github)
          cd .github
          rm -rf !(workflows)
          cd workflows
          rm -rf !(*)

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Commit and push deletions
        run: |
          git add -A
          git commit -m "Deleted everything except .github/workflows" || echo "Nothing to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
